abstract final class AppRoutes {
  static const root = '/';
  static const login = '/login';
  static const home = '/home';
  static const quotas = '/quotas';
  static const services = '/services';
  static const profile = '/profile';
  static const notifications = '/notifications';
  static const settings = '/settings';
  static const support = '/support';
  static const statement = '/quotas/statement';
  static const creditRelease = '/quotas/credit-release';
  static const quotaDetails = '/quota-details';
  static const vehicleQuotaDetails = '/vehicle-quota-details';
  static const servicesQuotaDetails = '/services-quota-details';
  static const installments = '/installments';
  static const bill = '/bill';
  static const assemblies = '/assemblies';
  static const assemblyDetails = '/assembly-details';
  static const bidOffer = '/bid-offer';
  static const bidConfigure = '/bid-configure';
  static const bidReview = '/bid-review';
  static const bidSuccess = '/bid-success';
  static const myBids = '/my-bids';
}
